### ISSUE TITLE
添加Peacefair Energy Monitor集成一直报错无法加载配置向导: {"message":"Invalid handler specified"}

### ISSUE THREAD

**Issue by 596311341** [georgezhao2010/peacefair_energy#14]
请问一下大家怎么解决啊？

**Comment by WalterDSU** [comment]
modbus.py
行2
from pymodbus.client.sync import ModbusTcpClient, ModbusUdpClient
改为
from pymodbus.client import ModbusTcpClient, ModbusUdpClient
行87,92 中的"unit"改成“slave”后可以正常工作了

**Comment by yoku70** [comment]
Hi, I have the same problem, could you write the solution in English, I can't translate it in your language.
Thank you
Livio from italy
