### ISSUE TITLE
No module named 'pymodbus.client.sync'

### ISSUE THREAD

**Issue by lujiashun1** [georgezhao2010/peacefair_energy#15]
升级了 ha t提示这个怎么办

**Comment by zch6348135** [comment]
对py不是很了解，但是参考pymodbus项目说明改了下代码，目前没报错。
文件位置custom_components/peacefair_energy/modbus.py
第2行改为
`from pymodbus.client import ModbusTcpClient, ModbusUdpClient`
第88行改为 
`return self._client.read_input_registers(address, count,slave=self._slave)`

**Comment by devang2** [comment]
Pull requests里有答案

**Comment by yoku70** [comment]
Hi, I have the same problem, could you write the solution in English, I can't translate it in your language.
Thank you
Livio from italy
