### ISSUE TITLE
关于日用电量（day_real）在每天8点更新的问题

### ISSUE THREAD

**Issue by hlhk2017** [georgezhao2010/peacefair_energy#17]
![QQ截图20230814082302](https://github.com/georgezhao2010/peacefair_energy/assets/32770630/8193ac6d-7a19-4491-9eef-21d52f7db122)
如图，ha的时区没有问题。不是很理解为什么更新在8点，但刚好像是时区的问题

**Comment by georgezhao2010** [comment]
你自己都知道问题所在了。

**Comment by hlhk2017** [comment]
有处理思路吗，我ha里按时间动作的自动化是准时的，但这个更新时间的问题又是时区的问题，不知道从哪儿下手更改啊
