### ISSUE TITLE
最新版不可用

### ISSUE THREAD

**Issue by owen263** [georgezhao2010/peacefair_energy#9]
是不是要更新什么？一直未知。

**Comment by weiqiye** [comment]
我也是，更新到最新版后就用不了了

**Comment by zy185750931** [comment]
> 我也是，更新到最新版后就用不了了 日志如下 Setup failed for custom integration peacefair_energy: Unable to import component: No module named 'pymodbus.client.sync' 看了下更新日志是python3.9升级成python3.10了 估计是pymodbus升级了的缘故

应该是的。看了下pymodbus的说明好像是API变更。不知道要咋改
PyModbus - API changes.
Version 3.1.0
Added --host to client_* examples, to allow easier use.
unit= in client calls are no longer converted to slave=, but raises a runtime exception.
Added missing client calls (all standard request are not available as methods).
client.mask_write_register() changed parameters.
server classes no longer accept reuse_port= (the socket do not accept it)

**Comment by weiqiye** [comment]
期待哪位大侠来指点下

**Comment by weiqiye** [comment]
> > 我也是，更新到最新版后就用不了了 日志如下 Setup failed for custom integration peacefair_energy: Unable to import component: No module named 'pymodbus.client.sync' 看了下更新日志是python3.9升级成python3.10了 估计是pymodbus升级了的缘故
> 
> 应该是的。看了下pymodbus的说明好像是API变更。不知道要咋改
> PyModbus - API changes.
> Version 3.1.0
> Added --host to client_* examples, to allow easier use.
> unit= in client calls are no longer converted to slave=, but raises a runtime exception.
> Added missing client calls (all standard request are not available as methods).
> client.mask_write_register() changed parameters.
> server classes no longer accept reuse_port= (the socket do not accept it)
> 

试了下把.sync去掉后，模块能加载了，但通讯没成功，提示unit参数有问题

**Comment by shuixinxing** [comment]
> > > 我也是，更新到最新版后就用不了了 日志如下 Setup failed for custom integration peacefair_energy: Unable to import component: No module named 'pymodbus.client.sync' 看了下更新日志是python3.9升级成python3.10了 估计是pymodbus升级了的缘故
> > 
> > 
> > 应该是的。看了下pymodbus的说明好像是API变更。不知道要咋改
> > PyModbus - API changes.
> > Version 3.1.0
> > Added --host to client_* examples, to allow easier use.
> > unit= in client calls are no longer converted to slave=, but raises a runtime exception.
> > Added missing client calls (all standard request are not available as methods).
> > client.mask_write_register() changed parameters.
> > server classes no longer accept reuse_port= (the socket do not accept it)
> 
> 试了下把.sync去掉后，模块能加载了，但通讯没成功，提示unit参数有问题

把.sync去掉，把87行和92行中的"unit"改成“slave”后可以正常工作了。

**Comment by weiqiye** [comment]
> > > > 我也是，更新到最新版后就用不了了 日志如下 Setup failed for custom integration peacefair_energy: Unable to import component: No module named 'pymodbus.client.sync' 看了下更新日志是python3.9升级成python3.10了 估计是pymodbus升级了的缘故
> > > 
> > > 
> > > 应该是的。看了下pymodbus的说明好像是API变更。不知道要咋改
> > > PyModbus - API changes.
> > > Version 3.1.0
> > > Added --host to client_* examples, to allow easier use.
> > > unit= in client calls are no longer converted to slave=, but raises a runtime exception.
> > > Added missing client calls (all standard request are not available as methods).
> > > client.mask_write_register() changed parameters.
> > > server classes no longer accept reuse_port= (the socket do not accept it)
> > 
> > 试了下把.sync去掉后，模块能加载了，但通讯没成功，提示unit参数有问题
> 
> 把.sync去掉，把87行和92行中的"unit"改成“slave”后可以正常工作了。

确实可行，感谢分享！

**Comment by SikaiGGMU** [comment]
楼上大神把pull request提上去？

**Comment by xiaxianguyue** [comment]
> > > > 我也是，更新到最新版后就用不了了 日志如下 Setup failed for custom integration peacefair_energy: Unable to import component: No module named 'pymodbus.client.sync' 看了下更新日志是python3.9升级成python3.10了 估计是pymodbus升级了的缘故
> > > 
> > > 
> > > 应该是的。看了下pymodbus的说明好像是API变更。不知道要咋改
> > > PyModbus - API changes.
> > > Version 3.1.0
> > > Added --host to client_* examples, to allow easier use.
> > > unit= in client calls are no longer converted to slave=, but raises a runtime exception.
> > > Added missing client calls (all standard request are not available as methods).
> > > client.mask_write_register() changed parameters.
> > > server classes no longer accept reuse_port= (the socket do not accept it)
> > 
> > 
> > 试了下把.sync去掉后，模块能加载了，但通讯没成功，提示unit参数有问题
> 
> 把.sync去掉，把87行和92行中的"unit"改成“slave”后可以正常工作了。

测试正常,感谢分享,我顺手提交了PR

**Comment by xiaxianguyue** [comment]
> > > > 我也是，更新到最新版后就用不了了 日志如下 Setup failed for custom integration peacefair_energy: Unable to import component: No module named 'pymodbus.client.sync' 看了下更新日志是python3.9升级成python3.10了 估计是pymodbus升级了的缘故
> > > 
> > > 
> > > 应该是的。看了下pymodbus的说明好像是API变更。不知道要咋改
> > > PyModbus - API changes.
> > > Version 3.1.0
> > > Added --host to client_* examples, to allow easier use.
> > > unit= in client calls are no longer converted to slave=, but raises a runtime exception.
> > > Added missing client calls (all standard request are not available as methods).
> > > client.mask_write_register() changed parameters.
> > > server classes no longer accept reuse_port= (the socket do not accept it)
> > 
> > 
> > 试了下把.sync去掉后，模块能加载了，但通讯没成功，提示unit参数有问题
> 
> 把.sync去掉，把87行和92行中的"unit"改成“slave”后可以正常工作了。

我的ha一直出现警告日志,
`Detected blocking call to sleep inside the event loop. This is causing stability issues. Please report issue to the custom integration author for peacefair_energy doing blocking calls at custom_components/peacefair_energy/modbus.py, line 88: return self._client.read_input_registers(address, count, **kwargs)`
能解决这个问题么
